config/routes.rb
SampleApp::Application.routes.draw do

  resources :restaurants do
    member do
      get 'orders'
      get 'upload'
      post 'import'
    end
  end
  
  resources :menu_sections
  resources :menu_items
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users,    :only => [:new, :create]
  
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
    
  post "orders/new"
  post "orders/confirm"
  post "orders/save"

  root :to => 'welcome#index'
  
  match '/search' => 'welcome#search', :via => :get

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu_section  
end

app/models/menu_section.rb
class MenuSection < ActiveRecord::Base
  belongs_to :restaurant
  has_many   :menu_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :order_items, :name, :phone, :restaurant_id
  serialize :order_items
  validates :name, :presence => true
  validates :phone, :presence => true
  belongs_to :restaurant
  
  default_scope order("created_at DESC")
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :presence => true
  validates :zip,  :presence => true 
  
  has_many :menu_sections
  has_many :users
  
  geocoded_by :zip
  after_validation :geocode
  
  default_scope order 'name'
  
  def has_menu_section?(section_name)
    self.menu_sections.select{ |s| s.name == section_name }.size > 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :restaurant_id, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates_uniqueness_of :email, :on => :create
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  
  def deny_access
    redirect_to login_path, :notice => "Please sign in to access this page"
  end
  helper_method :deny_access
  
   def create_formatted_order_items(order_items)
     order_items_formatted = Hash.new
     order_items.each do |item_id, qty|
       order_items_formatted[MenuItem.find(item_id)] = qty.to_i
     end
     order_items_formatted
   end
   helper_method :create_formatted_order_items
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def create
     @menu_item = MenuItem.new(params[:menu_item])
      @menu_item.save
      respond_to do |format|
        format.html { redirect_to @menu_item.menu_section.restaurant }
        format.js
      end
  end

  def destroy
  end

end

app/controllers/menu_sections_controller.rb
class MenuSectionsController < ApplicationController
  def create
    @menu_section = MenuSection.new(params[:menu_section])
    @menu_section.save
    respond_to do |format|
      format.html { redirect_to @menu_section.restaurant }
      format.js
    end
  end
  
  def destroy
    menu_section = MenuSection.find(params[:id])
    menu_section.destroy if menu_section
    respond_to do |format|
      format.html { redirect_to menu_section.restaurant }
      format.js
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController  
  def new
    @order_items = params[:order_items]
    @order_items.delete_if{ |key,value| value.to_i <= 0 }
  
    @order_items_formatted = create_formatted_order_items(@order_items)
   
    @order = Order.new(params[:order])
    @order.order_items = @order_items
    
    render 'delivery'
  end

  def save
    @order = Order.new(params[:order])
    @order.order_items = eval(@order.order_items)
    @order_items_formatted = create_formatted_order_items(@order.order_items)
    if @order.save
      render 'complete'
    else
      flash.now[:error] = "Please supply name and phone"
      render 'delivery'
    end
  end  
end

app/controllers/restaurants_controller.rb
require 'orders_helper'

class RestaurantsController < ApplicationController
  before_filter :authenticate, :only => [:new, :create]
  before_filter :authenticate_restaurant_user, :only => [:orders, :upload, :import]
  
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    
    @order = Order.new
        
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(params[:restaurant])
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_url
  end
  
  def orders
    @orders = Order.find_all_by_restaurant_id(params[:id])
    @order_items = {}
    @orders.each{|o| @order_items[o.id] = []; o.order_items.each_pair{|k,v| @order_items[o.id] <<  v + " x " + MenuItem.find(k).name } }
  end
  
  def upload 
  end
  
  def import
    @restaurant = Restaurant.find(params[:id])
    file = params[:file]
    open(file.path).each { |line| process_import_line(line, @restaurant) }
    redirect_to @restaurant
  end
  
  private

   def authenticate
     deny_access unless current_user && current_user.admin
   end
   
   def authenticate_restaurant_user
     if current_user && current_user.restaurant == Restaurant.find(params[:id])
      return
    else
      authenticate
    end
   end
   
   def process_import_line(line, restaurant)
     (section, name, price) = line.split(',')
     restaurant.menu_sections.create!({:name => section}) unless restaurant.has_menu_section?(section)
     MenuSection.find_by_restaurant_id_and_name(restaurant.id, section).menu_items.create!(:name => name, :price => price)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if (user.admin?)
        redirect_to root_path, :notice => "Logged in as admin"
      else
        redirect_to restaurant_path(user.restaurant), :notice => "Logged in"
      end
    else
      flash.now.alert = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "User #{@user.email} created"
    else
      render "new"
    end
  end
  
  private
  
  def authenticate
    deny_access unless current_user && current_user.admin
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def search
    @query_string = params[:query]
    @restaurants = Restaurant.near(@query_string, 100)
    if @restaurants.empty?
      @restaurants = Restaurant.all[0..4]
    end
    flash.now[:notice] = "No results found in your area, returning 5 other results"
    render :results
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menu_sections_helper.rb
module MenuSectionsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  


end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/menu_items/create.html.erb
<h1>MenuItems#create</h1>
<p>Find me in app/views/menu_items/create.html.erb</p>

app/views/menu_items/create.js.erb
$('#section<%= @menu_item.menu_section.id %>').append('<%= render :partial => "restaurants/menu_item", :object => @menu_item %>').hide().fadeIn(500);

app/views/menu_items/destroy.html.erb
<h1>MenuItems#destroy</h1>
<p>Find me in app/views/menu_items/destroy.html.erb</p>

app/views/menu_sections/create.html.erb
<h1>MenuSections#create</h1>
<p>Find me in app/views/menu_sections/create.html.erb</p>

app/views/menu_sections/create.js.erb
$('#sections_wrapper').append('<div class="menusection"><%= @menu_section.name %></div>').hide().fadeIn(500);

app/views/orders/_order_item_summary.html.erb
<h3>Items</h3>
<table>
	<tr>
		<th>Item</th>
		<th>Quantity</th>
		<th>Price</th>
		<th>Subtotal</th>
	</tr>
	<% order_total = 0.0 %>
	<% @order_items_formatted.each do |item,qty| %>
		<% order_total += item.price * qty %>
		<tr>
			<td><%= item.name %></td>
			<td><%= qty %></td>
			<td>$<%= item.price %></td>
			<td>$<%= item.price * qty %></td>
		</tr>
	<% end %>
	<tr><td colspan="3">Order total:</td><td>$<%= order_total %></td></tr>
</table>

app/views/orders/complete.html.erb
<h2>Your order is complete!</h2>
<h3>Enjoy your delicious food.</h3>

<p>
Restaurant: <%= @order.restaurant.name %><br/>
Name: <%= @order.name %><br/>
Phone: <%= @order.phone %>
</p>

<%= render :partial => 'order_item_summary' %>

app/views/orders/delivery.html.erb
<h2>Order Details: <%= @order.restaurant.name %></h2>

<%= render :partial => 'order_item_summary' %>

<h3>Delivery Info</h3>
<%= form_for(@order, :url => orders_save_path) do |f| %>
	<%= f.hidden_field :restaurant_id %>

	<%= hidden_field_tag 'order[order_items]', @order.order_items.to_s %>
	<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
	</div>
	<div class="field">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	</div>
	<div class="action">
	<%= f.submit "Submit order" %>
	</div>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_menu_item.html.erb
	<%= text_field_tag "order_items[" + menu_item.id.to_s + "]",nil, :size => 2 %>&nbsp; <%= menu_item.name %> <%= number_to_currency menu_item.price %><br/>

app/views/restaurants/_menu_section.erb
<p>
<div class="menusection"><%= menu_section.name %></div>
<%= render :partial => "restaurants/menu_item", :collection => menu_section.menu_items %>
</p>

app/views/restaurants/_restaurant.html.erb
<h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
<h3>Zip code: <%= restaurant.zip %></h3>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Zip Code</th>
    <th></th>
    <th></th>
  </tr>

<% @restaurants.each do |restaurant| %>
  <tr>
    <td><%= link_to restaurant.name, restaurant %></td>
    <td><%= restaurant.zip %></td>
	<% if current_user && current_user.admin %>
	    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
	    <td><%= link_to 'Destroy', restaurant, confirm: 'Are you sure?', method: :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/orders.html.erb
<h2>Recent Orders</h2>

<table>
	<% @orders.each do |o| %>
		<tr>
			<td><%= l o.created_at, :format => :long  %></td>
			<td><%= o.name %></td>
			<td><%= o.phone %></td>
			<td>
				<ul>
					<% for oi in @order_items[o.id] %>
						<li><%= oi %></li>
					<% end %>
				</ul>
			</td>
		</tr>
	<% end %>
</table>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<%= form_for(@order, :url => orders_new_path, :method => "post") do |f| %>

<%= hidden_field_tag "order[restaurant_id]", @restaurant.id %>

<div id="sections_wrapper">
<% @restaurant.menu_sections.each do |section| %>

	<div class="menusection"><%= section.name %></div>
	<div id="section<%= section.id %>">
	<% section.menu_items.each do |menu_item| %>
		<%= render :partial => "restaurants/menu_item", :object => menu_item %>
	<% end %>
	</div>

<% end %>
</div>


<%= submit_tag "Submit order" %>
<% end %>

<% if (current_user && current_user.restaurant == @restaurant) || (current_user && current_user.admin) %>
<%= form_for @restaurant.menu_sections.build, :remote => true do |f| %>
	<%= f.text_field :name %>
	<%= f.hidden_field :restaurant_id %>
	<%= f.submit "Create new menu section" %>
<% end %>

<%= form_for MenuItem.new, :remote => true do |f| %>
	Name: <%= f.text_field :name %> Price: $<%= f.text_field :price, :size => 2 %>
	<%= f.collection_select :menu_section_id, @restaurant.menu_sections, :id, :name %>
	<%= f.submit "Create new menu item" %>
<% end %>

<% end %>

app/views/restaurants/upload.html.erb
<h2>Import Menu Items from CSV</h2>

<p>
	Expected columns are Section, Description, Price
</p>
<%= form_tag "import", :multipart => true  do %>
  CSV File:
  <%= file_field_tag :file %>
  <br/>
  <%= submit_tag "Upload" %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= form_for(@user, :url => users_path) do |f| %>
  <% if @user.errors.any? %>
	<div class="error">
		<h2>Invalid user</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

<div class="field">
	<%= f.label :restaurant %>
	<%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>

app/views/welcome/_search_form.html.erb
<%= form_tag search_path, :method => 'get' do %>
  <%= text_field_tag :query %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/welcome/index.html.erb
<h2>Welcome</h2>
<p>Welcome to FoodFinder. Please enter your zip code below to find restaurants in your area.</p>

<%= render :partial => 'search_form' %>

app/views/welcome/results.html.erb
<h1>Search Results</h1>

<p>You searched on: <%= @query_string %></p>

<%= render @restaurants %>


<h3>New search</h3>
<%= render :partial => 'search_form' %>